Component constructor may set its `author`
CycloneDX/cyclonedx-node-module pull request #247
Opened 2022-01-26 17:53 UTC by jkowalleck

fixes #246

2022-01-26 18:53 UTC, shiraze commented
I think code should follow existing pattern, so:
```
this._author = (pkg.author?.name) ? pkg.author.name : undefined
```

And the expectation is that `package.json` would contain
```
...
 "author": { "name": "a name" },
...
```

Having said that, though, your code change would also be correct, but wouldn't it be better to use the "private" _author field?

2022-01-27 17:38 UTC, jkowalleck commented
re https://github.com/CycloneDX/cyclonedx-node-module/pull/247#issuecomment-1022493733
i thing the current code base is a mess and i dont want to continue like this anymore.
current code has proper setters for everything, and they do proper type checking - which is required to produce the proper XML/JSON results.

WHY on earth would one use the internal properties that are not type safe at all, if there are proper setters with type checks? 

no, in don't think i will use the internal properties. i'll use the existing setters.

but i will use the optional-property style you suggested, @shiraze . thanks for the hint :+1:

2022-01-27 20:17 UTC, shiraze requested changes
As discussed in conversation set using optional property style, and we're all good :)

2022-01-27 21:40 UTC, jkowalleck commented
na, cannot use shorthand ala `pkg.author?.name` - it is not supported by node12 - which is the lowest supported version. 
see https://github.com/CycloneDX/cyclonedx-node-module/runs/4972957766?check_suite_focus=true

2022-01-28 07:50 UTC, jkowalleck commented on model/Component.js
> +  #type = 'library'
@sonatype-lift help

2022-01-28 07:52 UTC, jkowalleck commented on model/Component.js
> +  #type = 'library'
@sonatype-lift ignore

2022-01-28 07:52 UTC, jkowalleck commented on model/Component.js
> +  #type = 'library'
@sonatype-lift ignore

2022-01-28 07:52 UTC, jkowalleck commented on model/Component.js
> +  #type = 'library'
@sonatype-lift ignore

2022-01-28 07:52 UTC, jkowalleck commented on model/Component.js
> +    return this.#supplier
@sonatype-lift ignore

2022-01-28 07:52 UTC, jkowalleck commented on model/Component.js
> +  #type = 'library'
@sonatype-lift ignore

2022-01-28 07:52 UTC, jkowalleck commented on model/Component.js
> +    this.#bomRef = this.validateType('bom-ref', value, String)
@sonatype-lift ignore

2022-01-29 16:33 UTC, jkowalleck commented on model/Component.js
> +  #type = 'library'
@sonatype-lift unignore

2022-01-29 20:32 UTC, jkowalleck commented on model/Component.js
> +  #type = 'library'
fixed

2022-02-01 18:02 UTC, brent-spiner commented on .github/workflows/nodejs.yml
> +          - "17"      # current
Seeing this just kinda reminded me that odd: 6 months, and even, 30 months. Can you start testing 18 yet or is it still pie in the sky?

2022-02-01 19:40 UTC, jkowalleck commented
@brent-spiner made my day

2022-02-02 19:00 UTC, merged